# Generated by Django 4.1.4 on 2023-01-08 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('contact', models.IntegerField()),
                ('package', models.CharField(max_length=25, unique=True)),
                ('stylistname', models.CharField(max_length=40, unique=True)),
                ('appointmentdate', models.TextField(null=True)),
                ('totalamount', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='stylist',
            name='bookeddates',
            field=models.TextField(null=True),
        ),
    ]
