# Generated by Django 4.1.4 on 2023-01-12 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_appointment_appointmentdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='bookingdate',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='totalamount',
            field=models.TextField(default=''),
        ),
    ]
